// This file is generated by scripts/build-gallery.mjs. Do not edit by hand.

export type GallerySource = { src: string; width: number; type: "image/webp" };

export type GalleryImage = {
  id: string;
  title: string;
  alt: string;
  width: number;
  height: number;
  animated: boolean;
  poster: string;
  original: string;
  sources: GallerySource[];
};

export const galleryImages: GalleryImage[] = [];
