import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import sharp from "sharp";

const root = process.cwd();
const sourceDirectory = path.resolve(
  root,
  process.env.GALLERY_SOURCE_DIR || path.join("gallery", "source"),
);
const outputDirectory = path.resolve(
  root,
  process.env.GALLERY_OUTPUT_DIR || path.join("public", "gallery", "generated"),
);
const manifestPath = path.resolve(
  root,
  process.env.GALLERY_MANIFEST_PATH
    || path.join("app", "gallery", "gallery-manifest.generated.ts"),
);
if (outputDirectory === root || outputDirectory === path.parse(outputDirectory).root) {
  throw new Error("GALLERY_OUTPUT_DIR must point to a dedicated generated-assets directory.");
}
const supportedExtensions = new Set([
  ".jpg",
  ".jpeg",
  ".png",
  ".webp",
  ".avif",
  ".heic",
  ".heif",
  ".tif",
  ".tiff",
  ".gif",
  ".apng",
]);
const targetWidths = [480, 960, 1600, 2400];

async function collectFiles(directory, prefix = "") {
  const entries = await readdir(directory, { withFileTypes: true }).catch(() => []);
  const files = [];

  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    if (entry.name.startsWith(".")) continue;
    const relativePath = path.posix.join(prefix, entry.name);
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await collectFiles(absolutePath, relativePath));
    else if (supportedExtensions.has(path.extname(entry.name).toLowerCase())) {
      files.push({ absolutePath, relativePath });
    }
  }

  return files;
}

function orientedDimensions(metadata) {
  const swapsAxes = metadata.orientation && metadata.orientation >= 5 && metadata.orientation <= 8;
  return {
    width: swapsAxes ? metadata.height : metadata.width,
    height: swapsAxes ? metadata.width : metadata.height,
  };
}

function slugify(relativePath) {
  const parsed = path.posix.parse(relativePath);
  return path.posix.join(parsed.dir, parsed.name)
    .normalize("NFKD")
    .replace(/[^a-zA-Z0-9\u4e00-\u9fff]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/\//g, "-")
    .toLowerCase() || "photo";
}

function titleFromPath(relativePath) {
  return path.posix.parse(relativePath).name
    .replace(/^\d{4}-/, "")
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function manifestSource(images) {
  return `// This file is generated by scripts/build-gallery.mjs. Do not edit by hand.\n\n`
    + `export type GallerySource = { src: string; width: number; type: "image/webp" };\n\n`
    + `export type GalleryImage = {\n`
    + `  id: string;\n  title: string;\n  alt: string;\n  width: number;\n  height: number;\n`
    + `  animated: boolean;\n  poster: string;\n  sources: GallerySource[];\n};\n\n`
    + `export const galleryImages: GalleryImage[] = ${JSON.stringify(images, null, 2)};\n`;
}

async function buildImage(file) {
  const input = await readFile(file.absolutePath);
  const hash = createHash("sha256").update(input).digest("hex").slice(0, 12);
  const probe = sharp(input, { animated: true, limitInputPixels: false });
  const metadata = await probe.metadata();
  const dimensions = orientedDimensions(metadata);

  if (!dimensions.width || !dimensions.height) {
    throw new Error(`Unable to read image dimensions: ${file.relativePath}`);
  }

  const animated = (metadata.pages ?? 1) > 1;
  const widths = [...new Set([
    ...targetWidths.filter((width) => width < dimensions.width),
    Math.min(dimensions.width, targetWidths.at(-1)),
  ])].sort((left, right) => left - right);
  const slug = slugify(file.relativePath);
  const sources = [];

  for (const width of widths) {
    const outputName = `${slug}-${hash}-${width}w.webp`;
    const outputPath = path.join(outputDirectory, outputName);
    const pipeline = sharp(input, { animated, limitInputPixels: false })
      .rotate()
      .resize({ width, withoutEnlargement: true });

    await pipeline.webp({
      quality: animated ? 82 : 84,
      effort: animated ? 4 : 5,
      smartSubsample: true,
    }).toFile(outputPath);
    sources.push({
      src: `/gallery/generated/${outputName}`,
      width,
      type: "image/webp",
    });
  }

  const placeholder = await sharp(input, { page: 0, limitInputPixels: false })
    .rotate()
    .resize({ width: 32, withoutEnlargement: true })
    .webp({ quality: 36, effort: 3 })
    .toBuffer();

  return {
    id: `${slug}-${hash}`,
    title: titleFromPath(file.relativePath),
    alt: titleFromPath(file.relativePath),
    width: dimensions.width,
    height: dimensions.height,
    animated,
    poster: `data:image/webp;base64,${placeholder.toString("base64")}`,
    sources,
  };
}

await mkdir(sourceDirectory, { recursive: true });
await mkdir(path.dirname(manifestPath), { recursive: true });
await rm(outputDirectory, { recursive: true, force: true });
await mkdir(outputDirectory, { recursive: true });

const files = await collectFiles(sourceDirectory);
const images = [];

for (const file of files) {
  try {
    images.push(await buildImage(file));
  } catch (error) {
    console.warn(`[gallery] Skipped ${file.relativePath}: ${error.message}`);
  }
}

await writeFile(manifestPath, manifestSource(images));
console.log(`[gallery] Built ${images.length} image${images.length === 1 ? "" : "s"}.`);
